version: "2.4"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 55432:5432
    env_file:
      - postgres.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
